services:
  db:
    image: mysql:8.0
    container_name: patient_monitoring_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patient_db
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - patient_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  ai_service:
    build: ./ai-service
    container_name: patient_ai_service
    ports:
      - "8000:8000"
    networks:
      - patient_net
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  backend:
    build: ./backend
    container_name: patient_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/patient_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - patient_net
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: patient_frontend
    ports:
      - "3000:3000"
    networks:
      - patient_net
    depends_on:
      - backend
    restart: on-failure

networks:
  patient_net:
    driver: bridge

volumes:
  db_data:
